#!/bin/bash
# Save the current opened GUI applications.
# And re-open or restore them
save()
{
    p_l=`wmctrl  -lp | awk  '{ print $3 }' | sort | uniq`
    for p in $p_l; do ps -q $p -f --no-headers | awk '{for(i=8;i<=NF;++i)printf $i""FS ; print ""}'  ;done > ~/Documents/current_opened_apps
}

restore()
{
    SAVEIFS=$IFS
    IFS=$(echo -en "\n\b")
    for command in `cat ~/Documents/current_opened_apps `; do bash -c "nohup  $command &"; done
    IFS=$SAVEIFS
   
}

if [ x"$1" = x"-s" -o x"$1" = x"--save" ]; then
    save
elif [ x"$1" = x"-r" -o x"$1" = x"--restore" ]; then
    restore
else
    echo "-s/--save 或 -r/--restore"
fi
